#Base
From ubuntu
#Maintainer / Verwalter
Maintainer Noa Violetti <noavioletti@hotmail.com>

#Build Image
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install apache2 -y

#Start Image
CMD ["systemctl start apache2"] 

# COPY src/ 
